language: go

go:
    - "1.13.1"

branches:
    only:
        - blog

install:
    - sudo apt-get install hugo

script:
    - hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    target_branch: master
    on:
        branch: blog
    local_dir: public

