language: go

go:
    - "1.13.1"

branches:
    only:
        - blog

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_0.68.3_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

script:
    - hugo

after_script:
    - cp CNAME LICENSE ./public

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    target_branch: master
    on:
        branch: blog
    local_dir: public

