
# This is a basic workflow to help you get started with Actions

name: Deploy GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - blog
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
        with:
          submodules: true
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
        
      - name: Build
        run: hugo --minify
      
      - name: Copy Files
        run: cp CNAME LICENSE ./public
          
      - name: Deploy
        env:
          USER_NAME: Github Actions
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GITHUB_REPO: github.com/isTianXin/isTianXin.github.io.git
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          TARGET_BRANCH: deploy
        run: |
          cd public
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git init && git add . && git commit -m 'Auto Build By Github Actions'
          git push --force --quiet "https://$GITHUB_TOKEN@$GITHUB_REPO" master:$TARGET_BRANCH
